F05 : Display menu products
Chermann-KING/crazee-burger pull request #5
Opened 2023-02-07 21:34 UTC by Chermann-KING

Creation of the <Card/> component and its hydration in the <Main/>

2023-02-08 20:59 UTC, vileaddev requested changes

2023-02-08 20:59 UTC, vileaddev commented on src/components/hoc/Card.js
> +    <CardStyled key={key} className="card">
```suggestion
    <CardStyled className="card">
```
le key doit toujours être à l'extérieur du composant pour que React sache s'il faut le conserver ou le détruire pour le remplacer par une autre instance de Card

2023-02-08 20:59 UTC, vileaddev commented on src/components/pages/order/Main/Main.js
> +            key={product.id}
ici tu peux et tu dois conserver key={id}, c'est très bien 💯

2023-02-08 20:59 UTC, vileaddev commented on src/components/pages/order/Main/Main.js
> +      {products.map((product) => {
je suis d'accord avec toi, j'aurai du l'appeler products qui était plus explicite 💯

2023-02-08 20:59 UTC, vileaddev commented on src/components/pages/order/Main/Main.js
> +    <MainStyled>
tu devrais créer un composant Menu ou Products dans lequel tu ranges le array.map car là tu sais que tu vas avoir Basket et Admin qui vont venir. Mettre directement dans le Main ça peut passer pour le moment mais littéralement au ticket d'après tu devras changer cette implémentation. En résumé, tu peux garder ça ici comme ça mais pas au prochain ticket.

2023-02-08 22:21 UTC, Chermann-KING commented on src/components/hoc/Card.js
> +    <CardStyled key={key} className="card">
Correction apportée

2023-02-08 22:25 UTC, Chermann-KING commented on src/components/pages/order/Main/Main.js
> +    <MainStyled>
Oui oui, c'est au programme selon que les tickets suivant s'imposent pour le faire. Sachant que le ticket encour ne l'exige pas, j'ai opté juste pour le respect des règle métier.

2023-02-10 17:29 UTC, vileaddev approved these changes
Je valide, bien joué Chermann 😉 ✅

2023-02-10 19:10 UTC, merged